### ISSUE TITLE
Migrate relevant issues

### ISSUE THREAD

**Issue by kenan-rhoton** [doner-kebard/card-game-backend#3]
**Description of the current situation**
All our issues are still in https://github.com/kenan-rhoton/card-game

**Description of the wanted situation**
The relevant backend issues should be here.

**Considered alternatives**
Writing them from scratch. Seems wasteful.

**Additional context**
They have to be copied manually cause Github doesn't support moving issues between projects... lol

**Comment by Masclins** [comment]
The only ones that might be relevant are:
- [API documentation](https://github.com/kenan-rhoton/card-game/issues/160)
- [Use HTTP status codes consistently](https://github.com/kenan-rhoton/card-game/issues/148)

@kenan-rhoton if you feel like this should be added, please do so (I leave it to you because I'm not sure if those should be here). Otherwise, please close the issue.

**Comment by kenan-rhoton** [comment]
Those both seem important for this project, I'll move them
